# Generated by Django 5.2.6 on 2025-09-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.game'),
            preserve_default=False,
        ),
    ]
